# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     BVS.Repo.insert!(%BVS.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias BVS.Negativation

[
  %{code: "00", description: "Operação bem Sucedida"},
  %{code: "16", description: "Calamidade pública"},
  %{code: "17", description: "Documento sob judice, bloqueado para novas inclusões"},
  %{code: "18", description: "Data Disp. Inválida, Negativação Expressa"},
  %{code: "19", description: "Inclusão não permitida registro suspenso"},
  %{code: "20", description: "Exclusão não permitida registro suspenso"},
  %{code: "21", description: "Indica códigos de erros do Tomador"},
  %{code: "22", description: "Indica códigos de erros do Avalista (ou Produto Óbito)"},
  %{code: "23", description: "Tipo do Devedor Inválido"},
  %{code: "24", description: "Indicador de Alteração Inválido ou Conflitante"},
  %{
    code: "25",
    description:
      "CPF Inexistente na Síntese Cadastral tente nova inclusão após 02 dias úteis (somente para inclusão no SCPC e UseCheque)"
  },
  %{
    code: "26",
    description:
      "Nome informado não confere com o nome da Síntese Cadastral (somente para inclusão no SCPC e UseCheque)"
  },
  %{code: "27", description: "Código de Barras Inválido"},
  %{code: "28", description: "Agência / Código do Cedente (Editado) Inválido"},
  %{code: "29", description: "Código do Cedente Inválido"},
  %{code: "30", description: "Nada Consta"},
  %{code: "31", description: "Registrado"},
  %{code: "32", description: "Documento ou Razão Social da Empresa Inválido"},
  %{code: "33", description: "Data de Vencimento do Débito Inválida"},
  %{code: "34", description: "Opção de Emissão do Boleto Inválida"},
  %{code: "35", description: "Carteira Inválida"},
  %{code: "36", description: "Nosso Número Inválido"},
  %{code: "37", description: "Dados da Empresa não Informados"},
  %{code: "38", description: "Dados do Boleto Bancário não Informado"},
  %{code: "39", description: "Não Autorizado a Consulta"},
  %{code: "40", description: "Documento do Débito Inválido"},
  %{code: "41", description: "Sistema Inválido"},
  %{code: "42", description: "Tipo de Registro Inválido"},
  %{code: "43", description: "Código de Operação Inválido"},
  %{code: "44", description: "Documento-1 Inválido"},
  %{code: "45", description: "Documento-2 Inválido"},
  %{code: "46", description: "Documento-3 Inválido"},
  %{code: "47", description: "Nome do Devedor Inválido"},
  %{code: "48", description: "Data de Nascimento do Devedor Inválida ou Inferior a 16 anos"},
  %{code: "49", description: "Nome do Cônjuge Inválido"},
  %{code: "50", description: "Data de Nascimento do Cônjuge Inválida ou Inferior a 16 anos"},
  %{code: "51", description: "Tipo de Endereço Inválido"},
  %{code: "52", description: "Endereço Inválido"},
  %{code: "53", description: "Bairro Inválido"},
  %{code: "54", description: "Número do CEP Inválido"},
  %{code: "55", description: "Cidade Inválida"},
  %{code: "56", description: "Unidade da Federação Inválida"},
  %{code: "57", description: "Código DDD Inválido"},
  %{code: "58", description: "Número do Telefone Inválido"},
  %{code: "59", description: "Ramal Inválido"},
  %{code: "60", description: "Número do Telex Inválido"},
  %{code: "61", description: "Número do Fax Inválido"},
  %{code: "62", description: "Data da Ocorrência Inválida"},
  %{code: "63", description: "Banco Inválido ou não Autorizado à Emissão do Boleto"},
  %{code: "64", description: "Agência ou Dígito Inválido"},
  %{code: "65", description: "Número do Cheque Inválido / Encontra-se como Sustado"},
  %{code: "66", description: "Motivo Inválido"},
  %{code: "67", description: "Valor Inválido"},
  %{code: "68", description: "Tipo de Cobrança Inválido"},
  %{code: "69", description: "Limite de Parcelas Inválido"},
  %{code: "70", description: "Praça Inválida"},
  %{code: "71", description: "Cartório Inválido"},
  %{code: "72", description: "Registro fora de Sequência"},
  %{code: "73", description: "Tipo de Ocorrência Inválido / Não Autorizado"},
  %{code: "74", description: "Documento de Protesto Inválido"},
  %{code: "75", description: "Contrato Inválido"},
  %{code: "76", description: "Documento do Avalista Inválido"},
  %{code: "77", description: "Tipo de Intercâmbio Inválido"},
  %{code: "78", description: "Nome do Intercâmbio Inválido"},
  %{code: "79", description: "Alínea Inválida / Não Permitida"},
  %{code: "80", description: "Naturalidade Inválida"},
  %{code: "81", description: "Contato Inválido"},
  %{code: "82", description: "Roteiro Inválido"},
  %{code: "83", description: "Forma de Pagamento Inválida"},
  %{code: "84", description: "Data Inicial de Cliente Inválida"},
  %{code: "85", description: "Tipo de Passagem / Crédito Inválido"},
  %{code: "86", description: "Endereço do Devedor / Correntista não Informado"},
  %{code: "87", description: "Endereço do Avalista não Informado"},
  %{code: "88", description: "Quantidade de Parcelas Inválida"},
  %{code: "89", description: "Estado Civil Inválido"},
  %{code: "90", description: "Devedor não Cadastrado"},
  %{code: "91", description: "Ocorrência Inexistente"},
  %{code: "92", description: "Avalista não Cadastrado"},
  %{code: "93", description: "Localidade para Consulta de SCPC (Intercâmbio) não Responde"},
  %{code: "94", description: "Localidade para Consulta de SCPC (Intercâmbio) Inexistente"},
  %{code: "95", description: "Exclusão de Ocorrência Não Permitida (Sistema ‘4’ - SRC)"},
  %{
    code: "96",
    description: "Contrato/Cheque em Duplicidade (somente para inclusão no SCPC e UseCheque)"
  },
  %{code: "97", description: "Conta Corrente ou Dígito Inválido"},
  %{code: "98", description: "Código de Cliente Inibido"},
  %{code: "99", description: "Entrar em Contato com a Boa Vista Serviços"},
  %{code: "5A", description: "Função Inválida"},
  %{code: "5B", description: "Erro na Sub-rotina - SIASDATA"},
  %{code: "5C", description: "Cód. Informante Inválido ou não Cadastrado"},
  %{code: "5D", description: "Tipo de Dado Inválido"},
  %{code: "5E", description: "Número do Título Inválido"},
  %{code: "5F", description: "Data de Vencimento Inválida"},
  %{code: "5G", description: "Indicador Anuência Inválido"},
  %{code: "5H", description: "Espécie do Título Inválido"},
  %{code: "5I", description: "Data de Emissão Inválida"},
  %{code: "5J", description: "Valor do Título Inválido"},
  %{code: "5K", description: "Valor do Saldo Inválido"},
  %{code: "5L", description: "Tipo de Moeda Inválido"},
  %{code: "5M", description: "Tipo de Endosso Inválido"},
  %{code: "5N", description: "Informação de Aceite Inválido"},
  %{code: "5O", description: "Ident.Vínculo Negativação Inválido"},
  %{code: "5P", description: "Nome Credor Inválido"},
  %{code: "5Q", description: "Nome do Titular da Conta Inválido"},
  %{code: "5R", description: "CEP Consumidor não Cadas. ou não Autor. p/ Protesto"},
  %{code: "5S", description: "Dados Cadastrais de Protesto não Encontrado"},
  %{code: "5T", description: "Dados Cadastrais de Protesto Incompleto"},
  %{code: "5U", description: "Inclusão de Protesto não Permitida"},
  %{code: "5V", description: "Protesto já Incluído - PRTI"},
  %{code: "5W", description: "Cancelamento Indevido - PRON"},
  %{code: "5X", description: "Cancelamento/Desistência Indevido - PRTI"},
  %{code: "5Y", description: "Cancelamento não Permitido - PRTI"},
  %{code: "5Z", description: "Desistência não Permitida - PRON"},
  %{code: "6A", description: "Desistência não Permitida - PRTI"},
  %{code: "6B", description: "Data de Distribuição Inválida ou Dias úteis Expirado"},
  %{code: "6C", description: "Número Ender. do Credor Atual Inválido"},
  %{code: "6D", description: "Tipo de Conta Inválido"},
  %{code: "6E", description: "Endereço do Titular da Conta Inválido"},
  %{code: "6F", description: "Número Ender. do Titular da Conta Inválido"},
  %{code: "6G", description: "Número do CEP do Titular da Conta Inválido"},
  %{code: "6H", description: "Informante não Autorizado - Protesto"},
  %{code: "6I", description: "Informante Inativo - Protesto"},
  %{code: "7A", description: "Movimento sem Registro Header"},
  %{code: "7B", description: "Versão Inválida"},
  %{code: "7C", description: "Processamento Inválido para Versão RP"},
  %{code: "7D", description: "Registro Header Inválido no Movto"},
  %{code: "7E", description: "Movimento Fora de Sequencia"},
  %{code: "7F", description: "Movimento em Duplicidade"},
  %{code: "7H", description: "Código de Serviço não Cadastrado"},
  %{code: "7I", description: "Código Primário não Cadastrado"},
  %{code: "7J", description: "Usuário não Cadastrado"},
  %{code: "7K", description: "Número do Movimento Inválido"},
  %{code: "7L", description: "Remessa já Processada"},
  %{code: "7M", description: "Movimento sem Registro Trailler"},
  %{code: "7N", description: "Código Informado Difere do Header"},
  %{code: "7O", description: "Data do Trailler Difere do Header"},
  %{code: "7P", description: "Movimento já Processado"}
]
|> Enum.map(&Negativation.create_return_code/1)

[
  %{code: "AD", description: "Adiantamento a depositantes - conta corrente devedora"},
  %{
    code: "AG",
    description: "Empréstimo / financiamento agrícola / rural- comercial industrial e custeio"
  },
  %{code: "AL", description: "Aluguel"},
  %{code: "AR", description: "Arrendamento, inclusive leasing"},
  %{code: "C1", description: "Consórcio imóvel"},
  %{
    code: "C2",
    description: "Consórcio veículos pesados: tratores, ônibus, caminhões, barcos e aviões"
  },
  %{code: "C3", description: "Consórcio veículos"},
  %{code: "C4", description: "Consórcio motocicletas e motonetas"},
  %{code: "C5", description: "Consórcio outros bens moveis"},
  %{code: "C6", description: "Consórcio passagens aéreas"},
  %{code: "CA", description: "Operações de financiamento de câmbio em geral"},
  %{code: "CB", description: "Contrato de cambio"},
  %{code: "CC", description: "Conta condominial"},
  %{code: "CD", description: "Crédito direto – crediário"},
  %{code: "CH", description: "Cheque"},
  %{code: "CI", description: "Cédula de credito industrial"},
  %{code: "CO", description: "Consórcio contemplado"},
  %{code: "CP", description: "Crédito pessoal"},
  %{code: "CR", description: "Cédula rural pignoratícia (impedidos de crédito rural pelo Bacen)"},
  %{code: "CS", description: "Contratos (diversos)"},
  %{code: "CT", description: "Operações com cartão de crédito"},
  %{code: "DC", description: "Dívidas originárias de cheques"},
  %{code: "DB", description: "Debêntures"},
  %{code: "DE", description: "Dívidas originárias de cheque eletrônico"},
  %{code: "DP", description: "Duplicata"},
  %{
    code: "EC",
    description:
      "Empréstimo em conta, conta corrente garantida, capital de giro, programa especial"
  },
  %{code: "EE", description: "Energia elétrica - faturas de fornecimento de luz"},
  %{code: "EG", description: "Empréstimo consignado"},
  %{code: "FG", description: "Gás faturas de fornecimento de gás"},
  %{code: "FI", description: "Créditos e financiamentos"},
  %{code: "HO", description: "Despesas com hospitais"},
  %{code: "IE", description: "Instituição de ensino"},
  %{code: "LC", description: "Letra de cambio"},
  %{code: "IM", description: "Operações imobiliárias"},
  %{code: "ME", description: "Mensalidades escolares"},
  %{code: "NE", description: "Nota de crédito exportação"},
  %{code: "NF", description: "Notas fiscais"},
  %{code: "NP", description: "Nota promissória"},
  %{code: "XX", description: "Natureza não especificada"}
]
|> Enum.map(&Negativation.create_ocurrence_type/1)
